production:
  adapter: postgresql
  host: ec2-54-243-229-57.compute-1.amazonaws.com
  database: d68rtln15e8hbr
  user: sembfxvxuvmimc
  password: jlZB7lwS3_P9g1fiH-0qjDecvY
  port: 5432

development:
  adapter: postgresql
  database: sign_in_with_twitter_dev
  host: localhost
  user: james
  password: 

test:
  adapter: postgresql
  database: sign_in_with_twitter_dev
  host: localhost
  user: james
  password: 